import time
print("------Practice Questions------\nBy Sophia Luo\n----------------")
time.sleep(2)
print("1. Which of the following are operators, and which are values?\n*, -, /, and + are all operators,\n'hello', -88.8, and 5 are all values.\n---------------------")
time.sleep(6)
print("2. Which of the following is a variable, and which is a string?\nspam is a variable,\n'spam' is a string.\n-------------------------")
time.sleep(6)
print("3. Name three data types.\nThree of the data types are a str, int, and float.\n------------------------")
time.sleep(6)
print("4. What is an expression made out of? What do all expressions do?\nAn expression is made out of numbers and values/strings that is equal to a number.\nAn expression just adds, subtracts, divides, multiplies, or mods numbers.\n---------------------")
time.sleep(6)
print("5. What is the difference between an expression and a statement?\nA expression is like a math equation, but a statement is just (something) = (A data type).\n-----------------------")
time.sleep(6)
print("6. What does the variable bacon contain after the following code?\n--------------\nCode:\nbacon = 20\nbacon + 1\n-----------\nThe variable bacon is now 21\n------------------------")
time.sleep(6)
print("7. What should the following two expressions evaluate to?\n---------------\nCode:\n'spam' + 'spampam'\n'spam' * 3\n-------------\nThe first line of the code is 'spamspampam', and the second line is 'spamspamspam'.\n-----------------")
time.sleep(6)
print("8. Why is eggs a valid variable name while 100 is not?\nThat is because eggs is a integer, but 100 is a number.\n-----------------")
time.sleep(6)
print("9. What three functions can be used to get the integer, float number, or string version of a value?\nYou can use the (something) = (str or float or int)((something))\nYou can also use if (something) == (str or int or float)((something))\nOr you can just use (something) = (str or int or float)\n-----------------------")
time.sleep(6)
print("10. Why does the expression cause an error? How can you fix it?\n-----------\nCode:\n'I eat' + 99 + 'burritos'\n------------\nThis is because 99 is a int, not a str, and only strings can be added to strings.\nYou can fix it by changing 99 to '99', which is a string and will work.\n-------------------------")
time.sleep(6)
print("Extra Credit:\nlen just tells you the number of stuff in lists or strings or ints.\nbin just make it into its 'binary' form, whatever that means...\nhex just turns numbers into, like, a code, for numbers, aka its 'hexadecimal' form.\n----------------------------")
time.sleep(2)
print("Thanks for watching my practice questions and my answers!")