my_tuple = ()
object1 = input("Enter your first object: ")
object2 = input("Enter your second object: ")
num1 = input("Enter your first number: ")
num2 = input("Enter your second number: ")
my_tuple += tuple(object1)
my_tuple += tuple(object2)
my_tuple += tuple(num1)
my_tuple += tuple(num2)
print(my_tuple)